-- =====================================================
-- resetSampleData.sql
-- Removes all data inserted by sampleData.sql.
--
-- Note: triggers will still fire during deletion and
-- will generate additional entries in audit_log. These
-- are cleaned up at the end of this script.
-- =====================================================

USE dars;
SET FOREIGN_KEY_CHECKS = 0;

-- =====================================================
-- Report UUIDs (must match sampleData.sql)
-- =====================================================
SET @r1 = 'RP-20260410-0001';
SET @r2 = 'RP-20260412-0001';
SET @r3 = 'RP-20260415-0001';
SET @r4 = 'RP-20260420-0001';
SET @r5 = 'RP-20260501-0001';
SET @r6 = 'RP-20260505-0001';

-- =====================================================
-- Delete child tables first
-- =====================================================
DELETE FROM dispatch
WHERE id IN (1, 2, 3, 4);

DELETE FROM resolved_report
WHERE report_id IN (@r1, @r2, @r3, @r4, @r5, @r6);

DELETE FROM report_status_history
WHERE report_id IN (@r1, @r2, @r3, @r4, @r5, @r6);

-- =====================================================
-- Delete reports
-- =====================================================
DELETE FROM report
WHERE id IN (@r1, @r2, @r3, @r4, @r5, @r6);

-- =====================================================
-- Delete reference data
-- =====================================================
DELETE FROM victim
WHERE id IN (1, 2, 3, 4, 5, 6);

DELETE FROM offender
WHERE id IN (1, 2, 3, 4);

DELETE FROM responder
WHERE id IN (1, 2, 3, 4);

DELETE FROM staff
WHERE id IN (1, 2, 3, 4, 5, 6);

DELETE FROM abuse_type
WHERE abuse_name IN ('Physical', 'Psychological', 'Sexual', 'Economic', 'Stalking');

DELETE FROM barangay
WHERE id IN (1, 2, 3, 4, 5);

-- =====================================================
-- Clean up all audit_log entries related to sample data
-- (including entries generated by this reset script)
-- =====================================================
DELETE FROM audit_log WHERE
    (table_name = 'report'          AND record_id IN (@r1, @r2, @r3, @r4, @r5, @r6)) OR
    (table_name = 'resolved_report' AND record_id IN (@r1, @r2, @r3, @r4, @r5, @r6)) OR
    (table_name = 'dispatch'        AND record_id IN ('1', '2', '3', '4')) OR
    (table_name = 'barangay'        AND record_id IN ('1', '2', '3', '4', '5')) OR
    (table_name = 'staff'           AND record_id IN ('1', '2', '3', '4', '5', '6')) OR
    (table_name = 'victim'          AND record_id IN ('1', '2', '3', '4', '5', '6')) OR
    (table_name = 'offender'        AND record_id IN ('1', '2', '3', '4')) OR
    (table_name = 'responder'       AND record_id IN ('1', '2', '3', '4')) OR
    (table_name = 'abuse_type'      AND record_id IN ('Physical', 'Psychological', 'Sexual', 'Economic', 'Stalking'));

-- =====================================================
-- Clean up report_id_seq rows for sample dates
-- =====================================================
DELETE FROM report_id_seq
WHERE seq_date IN ('2026-04-10', '2026-04-12', '2026-04-15', '2026-04-20', '2026-05-01', '2026-05-05');

-- =====================================================
-- Reset auto_increment counters
-- =====================================================
ALTER TABLE barangay  AUTO_INCREMENT = 1;
ALTER TABLE staff     AUTO_INCREMENT = 1;
ALTER TABLE victim    AUTO_INCREMENT = 1;
ALTER TABLE offender  AUTO_INCREMENT = 1;
ALTER TABLE responder AUTO_INCREMENT = 1;
ALTER TABLE dispatch  AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;